services:


# --------
# ContactBundle
# --------

    PiedWeb\ContactBundle\PiedWebContactBundle: ~

    PiedWeb\ContactBundle\:
        autowire: true
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    PiedWeb\ContactBundle\Controller\:
        autowire: true
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']
